name: example
description: Example app
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  vm_service: ^15.0.0

dev_dependencies:
  build_runner:
  keys_generator:
    path: ..