name: keys_generator
description: Keys class hierarchy generator from Yaml files.
version: 1.0.4
repository: https://github.com/nogipx/keys_generator

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.0
  build: ^2.4.1
  source_gen: ^1.2.5

dev_dependencies:
  build_runner: 2.4.9
  lints: ^4.0.0
  test: ^1.24.0
